name: .NET Core

on:
  push:
    branches: [ next ]
    paths-ignore:
      - '**/README.md'
      - 'assets/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Build Windows X64
      run: dotnet publish --configuration Release --self-contained -r win-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:Version=1.0.${{ github.run_number }} -o build-win-x64 ./Wasari.Cli/Wasari.Cli.csproj
    - name: Build Linux X64
      run: dotnet publish --configuration Release --self-contained -r linux-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:Version=1.0.${{ github.run_number }} -o build-linux-x64 ./Wasari.Cli/Wasari.Cli.csproj
    - name: Create versioned release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ github.run_number }}"
        prerelease: true
        title: 'Build NEXT #${{ github.run_number }}'
        files: |
          build-win-x64/Wasari.Cli.exe
          build-linux-x64/Wasari.Cli